### ISSUE TITLE
"mysql://admin@password@localhost:3306/db" in readme is not working

### ISSUE THREAD

**Issue by kenyhenry** [zjunior-infra/Dashboard#23]
in fact the correct link is:

`mysql://user:password@localhost:3306/db`

and 'admin' user is not set by default it is 'user'

**Comment by Mahmoudgalalz** [comment]
so does that work with you, I updated the docker-compose file but I didn't push it 
so does your solution work @kenyhenry

**Comment by kenyhenry** [comment]
certainly, '@' mean the address. if you want to connect the user and password must be seperate by ':' otherwise it tel you that you are trying to connect without password and try to connect to the website "password" then "localhost:3306".
On my side '@' not working only ':' work.
You can try it on your side.

Also, i want to contribute.

**Comment by kenyhenry** [comment]
Also, in the code .env file is not retrieve to get MAIN_DATABASE_URL env var.
to be more explicit you can run:

`MAIN_DATABASE_URL=mysql://user:password@localhost:3306/db  npx prisma db seed`

`MAIN_DATABASE_URL=mysql://user:password@localhost:3306/db  npm run dev`

or install dotenv 

`npm install dotenv`

and retrieve the var with :

`require('dotenv').config();`
`const myEnvVariable = process.env.MAIN_DATABASE_URL;`

**Comment by kenyhenry** [comment]
and the design of the website is really cool 👍

**Comment by Mahmoudgalalz** [comment]
> Also, in the code .env file is not retrieve to get MAIN_DATABASE_URL env var. to be more explicit you can run:
> 
> `MAIN_DATABASE_URL=mysql://user:password@localhost:3306/db npx prisma db seed`
> 
> `MAIN_DATABASE_URL=mysql://user:password@localhost:3306/db npm run dev`
> 
> or install dotenv
> 
> `npm install dotenv`
> 
> and retrieve the var with :
> 
> `require('dotenv').config();` `const myEnvVariable = process.env.MAIN_DATABASE_URL;`

nextjs inject .env file automatically so you just have to create the .env file within the root-dir


so all you have to do to follow the doc, and thinks for the correcting the doc, 
you can send your PR with this fix
